wget http://ftp.luoo.net/radio/radio394/01.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Fall Rain.mp3"
wget http://ftp.luoo.net/radio/radio394/02.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/여름날의 소풍.mp3"
wget http://ftp.luoo.net/radio/radio394/03.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Prodigal.mp3"
wget http://ftp.luoo.net/radio/radio394/04.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Refrain.mp3"
wget http://ftp.luoo.net/radio/radio394/05.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/그날도 오늘처럼 비가 왔죠.mp3"
wget http://ftp.luoo.net/radio/radio394/06.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Early Morning Roof.mp3"
wget http://ftp.luoo.net/radio/radio394/07.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/The Voyage.mp3"
wget http://ftp.luoo.net/radio/radio394/08.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Far Away Here.mp3"
wget http://ftp.luoo.net/radio/radio394/09.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/I Will Stand By You.mp3"
wget http://ftp.luoo.net/radio/radio394/10.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Mary's Hymn.mp3"
wget http://ftp.luoo.net/radio/radio395/01.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/小木船.mp3"
wget http://ftp.luoo.net/radio/radio395/02.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/漂.mp3"
wget http://ftp.luoo.net/radio/radio395/03.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/Inanga/湖.mp3"
wget http://ftp.luoo.net/radio/radio395/04.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/欺骗.mp3"
wget http://ftp.luoo.net/radio/radio395/05.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/星星堆满天.mp3"
wget http://ftp.luoo.net/radio/radio395/06.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/分心.mp3"
wget http://ftp.luoo.net/radio/radio395/07.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/我知道你收藏我.mp3"
wget http://ftp.luoo.net/radio/radio395/08.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/三个人的晚餐.mp3"
wget http://ftp.luoo.net/radio/radio395/09.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/反正.mp3"
wget http://ftp.luoo.net/radio/radio395/10.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/你的独舞.mp3"
wget http://ftp.luoo.net/radio/radio395/11.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/距离.mp3"
wget http://ftp.luoo.net/radio/radio395/12.mp3 -O "C:\Users\honghe\PycharmProjects\helloPython\org\honghe\hello/往高雄的最后一班车没有歌声.mp3"
